import mongoose from "mongoose";

const ResumeSchema = new mongoose.Schema({
   studentname:{
      type:String,
      required:true
   },
   user:{
     type:mongoose.Types.ObjectId,
     ref:"User",
     required:true
   },
   gender:{
    type:String,
    required:true
   },
   email:{
    type:String,
    required:true,
   },
   mobilenumber:{
      type:String,
      required:true,
      max:10
   },
   address:{
    type:String,
    required:true,
   },
   projectname:{
    type:String,
    required:true
   },
   projectdesc:{
    type:String,
    required:true
   },
   Education:{
    type:String,
    required:true
   },
   graduationstartyear:{
    type:Date,
    required:true
   },
   graduationendyear:{
    type:Date,
    required:true
   },
   worktitle:{
    type:String,
    required:false
   },
   workdesc:{
    type:String,
    required:false
   },
   skills:{
    type:String,
    required:true
   },
   certifications:{
    type:String,
    required:false
   },
   linkdin:{
    type:String,
    required:true
   },
   facebook:{
    type:String,
    required:false
   },
   fathername:{
    type:String,
   },
   sscschool:{
    type:String,
    required:true
   },
   hsccollege:{
    type:String,
    required:true
   },
   graduationcollege:{
    type:String,
    required:true
   },
   sscpassingDate:{
    type:Date,
    required:true
   },
   hscpassingDate:{
    type:Date,
    required:true
   },
   graduationpassingDate:{
    type:Date,
   },
   sscPercentage:{
    type:Number,
    min:35,
    max:100
   },
   hscPercentage:{
    type:Number,
    min:35,
    max:100
   },
   graduationPercentage:{
    type:Number,
    min:35,
    max:100
   }


})

export default mongoose.model("Resume",ResumeSchema)